spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /ks
    username: guest
    password: guest
    connection-timeout: 1s # 设置 MQ 的连接超时时间
    # 生产者重连
    template:
      retry:
        enabled: true
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial - interval * multiplier
        max-attempts: 3 # 最大重试次数
    # 生产者确认
    publisher-confirm-type: correlated # 开启 publisher confirm 机制；有三种模式：none 表示关闭 confirm 机制；simple 表示同步阻塞等待 MQ 的回执消息；correlated MQ 异步回调方式返回回执消息
    publisher-returns: true # 开启 publisher return 机制

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.yq: debug