server:
  port: 8080



sw:
  sensitive: # 敏感词校验相关配置
    enable: true
    deny: # 自定义的敏感词，英文逗号分割
    allow: # 自定义的非敏感词，英文逗号分割

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/road_map?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yq.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl