spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/road_map?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yq.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl